# Generated by Django 2.1.2 on 2018-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20181020_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
