# Generated by Django 2.1.2 on 2018-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181005_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamreal',
            name='document',
            field=models.FileField(null=True, upload_to='not required'),
        ),
    ]
