# Generated by Django 2.1.2 on 2018-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dreamreal_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'credential',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='not required')),
                ('credential', models.ManyToManyField(to='myapp.Credential')),
            ],
            options={
                'db_table': 'document',
                'ordering': ('document',),
            },
        ),
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
