# Generated by Django 2.1.2 on 2018-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181008_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('filename',)},
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='filepath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
