# Generated by Django 2.1.2 on 2018-10-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181008_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('document',)},
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='document',
            name='filepath',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='not required'),
        ),
    ]
