# Generated by Django 2.1.2 on 2018-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181008_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.BinaryField(null=True),
        ),
    ]
